### ISSUE TITLE
is this stil active?

### ISSUE THREAD

**Issue by abast** [tritemio/nbrun#2]
This seems to be exactly what I was looking for. Apparently, there has not been much development during the last months. Is this because there is nothing to improve and "it just works" or is it maybe deprecated for some reason?

**Comment by arc12** [comment]
I use it to maintain standard analysis notebooks which I use for differnt clients, setting per-client parameters as necessary.
It does "just work", although you might find room for enhancements according to your scenario.

**Comment by tritemio** [comment]
Yes it just works and I am still using it in several projects. The code is only one python file with 2 functions that I copy in the notebook folder. Occasionally, if I need little tweaks to customize it for different projects, I apply them in place.

nbrun uses `eval` to interpret the "parameters" cell which is not very clean. The advantage is that it supports any variable type with literal representation, i.e. scalars, strings and lists/dict of scalars/strings.

There is another project by @takluyver that uses AST instead of eval (https://github.com/takluyver/nbparameterise). However the code is much more complex and, last time I checked, it didn't support list or dict. I thought about improving `nbparameterise` but at the end I didn't find the time since `nbrun` was already working for all the use-cases I needed.

So, I doubt there will be tons of development here. But I'll accept PR request for improvements that are general and don't make the code too complex. While I write, I realize I didn't fulfil my own intentions, since I totally forgot #1 by @arc12, I apologize. I think the ability to customize the template folder for is worthwhile, I'll merge the PR shortly.

**Comment by abast** [comment]
Thanks for the quick and detailed response!

**Comment by ajasja** [comment]
@tritemio nbrun looks great (I've been looking at standard runipy and nbparametrize as well). I almost posted a duplicate questions, so perhaps the gist of this issue could go into the readme (under a development section)?

**Comment by tritemio** [comment]
Sure I'll do that, thanks for the interest.
